FROM node:16-alpine
RUN apk --no-cache add openjdk11-jre bash
COPY ["./firebase.json", ".firebaserc", "./database.rules.json", "./storage.rules", "./"]
RUN npm install --location=global firebase-tools
RUN firebase setup:emulators:database && \
  firebase setup:emulators:storage && \
  firebase setup:emulators:ui
CMD ["firebase", "emulators:start", "--export-on-exit=./firebase-emulator-data", "--import=./firebase-emulator-data", "--only=database,storage,auth"]